meta_product_name: "Hans Preeker"
meta_title: "Fullstack developer"
meta_description: "An enthousiastic full stack developer with a passion for creating new experiences for others.
My current stack is Ruby on rails, HTML5, CSS, Javescript and MySQL."
meta_image: "coverimage.png"